---

version: "3.5"

services:
  # CHORDS Rails application: nginx + rails + CHORDS rails code
  chords:
    container_name: chords_app
    image: ncareol/chords:1.0.1
    volumes:
      - mysql-data:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-tmp:/tmp/
      - nginx-log:/var/log/nginx
      - rails-log:/chords/log
    environment:
      - RAILS_ENV=production
      - CHORDS_ADMIN_PW=admin
      - CHORDS_GUEST_PW=guest
      - SECRET_KEY_BASE=secretbase
      - DB_RETENTION=inf
      - DOCKER_TAG=1.0.1
      #- CHORDS_EMAIL_SERVER=${CHORDS_EMAIL_SERVER}
      #- CHORDS_EMAIL_PORT=${CHORDS_EMAIL_PORT}
      #- CHORDS_EMAIL_ADDRESS=${CHORDS_EMAIL_ADDRESS}
      #- CHORDS_EMAIL_PASSWORD=${CHORDS_EMAIL_PASSWORD}
      - WORKERS=4
      # Note: INFLUXDB_ variables are used by the Influxer gem, meaning that
      # you should NOT create your own variables beginning with INFLUXDB_.
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    command: bash -c "dos2unix ./chords_start.sh && chmod a+x ./chords_start.sh && ./chords_start.sh"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    ports:
        - 3080:80
    links:
      - mysql
      - influxdb

  # Rails mysql database
  mysql:
    container_name: chords_mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=chords_demo_user
      - MYSQL_PASSWORD=password
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  # InfluxData influxdb time-series database
  influxdb:
    container_name: chords_influxdb
    image: influxdb:1.6
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-log:/var/log/influxdb
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-tmp:/tmp/
    environment:
      - INFLUXDB_HTTP_MAX_ROW_LIMIT=1000000
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 8086:8086
      - 8083:8083

  # InfluxData kapacitor time series monitoring
  kapacitor:
    container_name: chords_kapacitor
    image: ncareol/kapacitor
    volumes:
      - kapacitor-data:/var/lib/kapacitor
      - kapacitor-log:/var/log/kapacitor
    environment:
      # Custom environment variable, used by ncareol/kapacitor
      - KAPACITOR_ENABLED=true
      #
      - KAPACITOR_HOSTNAME=chords_kapacitor
      - KAPACITOR_LOGGING_LEVEL=INFO
      - KAPACITOR_REPORTING_ENABLED=false
      #
      - KAPACITOR_HTTP_AUTH_ENABLED=true
      #
      - KAPACITOR_INFLUXDB_0_URLS_0=http://chords_influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=admin
      - KAPACITOR_INFLUXDB_0_PASSWORD=admin
      #
      - KAPACITOR_SMTP_ENABLED=true
      #- KAPACITOR_SMTP_FROM=${CHORDS_EMAIL_ADDRESS}
      #- KAPACITOR_SMTP_HOST=${CHORDS_EMAIL_SERVER}
      #- KAPACITOR_SMTP_PORT=${CHORDS_EMAIL_PORT}
      #- KAPACITOR_SMTP_USERNAME=${CHORDS_EMAIL_ADDRESS}
      #- KAPACITOR_SMTP_PASSWORD=${CHORDS_EMAIL_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 9092:9092
    links:
      - chords

  streams:
      container_name: streams-api
      image: tapis/streams-api
      ports:
          - "5000:5000"
      volumes:
          - ./config-local.json:/home/tapis/config.json
          - ./service.log:/home/tapis/service.log
      depends_on:
          - chords
          - influxdb
          - mysql
          - kapacitor

volumes:
  # CHORDS Rails meta-data
  mysql-data:
  # CHORDS time-series data
  influxdb-data:
  # kapacitor data
  kapacitor-data:
  #shared_tmp volume
  shared-tmp:
  # log directories
  rails-log:
  nginx-log:
  mysql-log:
  influxdb-log:
  kapacitor-log:
